/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Document
         * @description Upload a JPEG, PNG, or HEIC photo to start editing it.
         */
        post: operations["createDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["getDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Project
         * @description The original photo and all its edits as one `.photoagent` file, to keep and reopen.
         */
        get: operations["downloadProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Graph
         * @description The full stored document (history, layers, chat), as kept for browser autosave.
         */
        get: operations["getGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Source
         * @description The original file exactly as uploaded.
         */
        get: operations["getSource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Undo
         * @description Step back one step in the history.
         */
        post: operations["undo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/redo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redo
         * @description Re-apply the most recently undone step.
         */
        post: operations["redo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/edits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit By Hand
         * @description Record a change made with the manual controls as a named step in the history.
         */
        post: operations["editByHand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Recipe
         * @description Add a recipe's layers on top of the current edits, as one step in the history.
         */
        post: operations["applyRecipe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/looks/{look_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Look
         * @description Add a look's layer on top of the current edits, as one step in the history.
         */
        post: operations["applyLook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/retouch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retouch Portrait
         * @description Add portrait retouch layers (skin, eyes, teeth) on top, as one step in the history;
         *     without options, the subtle defaults.
         */
        post: operations["retouchPortrait"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/straighten": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auto Straighten
         * @description Level the photo and square up converging verticals, measured from its straight
         *     lines, as one step in the history. 422 when it finds nothing to go by.
         */
        post: operations["autoStraighten"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Checkout
         * @description Jump to any step in the history. Editing from there starts a new branch; the steps
         *     after it stay in the history.
         */
        post: operations["checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/original": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Original
         * @description The unedited photo at preview size, as JPEG (browsers cannot show HEIC).
         */
        get: operations["getOriginal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview
         * @description The photo with the current edits applied, at preview size, as JPEG.
         *
         *     Add `?revision=<document revision>` to make the URL unique per edit state; the response
         *     is the current state either way.
         */
        get: operations["getPreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export
         * @description Render the edits at full resolution and return the file to download.
         */
        post: operations["exportDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/before": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Before
         * @description The unedited look with the current framing (crop, rotation, flips) applied, so it lines
         *     up with the preview for before/after comparison.
         */
        get: operations["getBefore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/layers/{layer_id}/mask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Layer Mask
         * @description Where a layer of the current state applies, at preview size, as a grayscale PNG
         *     (white is full effect). Add `?revision=` to make the URL unique per edit state.
         */
        get: operations["getLayerMask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description AI model jobs running (or just finished) for this document, with their progress.
         *     The web app polls this while it waits on a change.
         */
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open Project
         * @description Reopen a saved project: either a `.photoagent` project `file`, or an `original`
         *     photo plus its `graph` (the document JSON), as the browser keeps them for autosave.
         *
         *     The project keeps its id unless another document already has it.
         */
        post: operations["openProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recipes
         * @description Saved recipes, newest first.
         */
        get: operations["listRecipes"];
        put?: never;
        /**
         * Create Recipe
         * @description Save a set of layers as a recipe to apply to other photos.
         */
        post: operations["createRecipe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Recipe */
        delete: operations["deleteRecipe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/looks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Looks
         * @description The built-in looks, each a layer of ordinary adjustments.
         */
        get: operations["listLooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report that the server is up and whether the Claude API key is set.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Operations
         * @description Every operation with its parameters' ranges, for building manual controls.
         */
        get: operations["listOperations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Models
         * @description Which model (or classical fallback) runs each AI task, and on what device.
         */
        get: operations["getModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AutoStraighten
         * @description What to fix automatically.
         */
        AutoStraighten: {
            /**
             * Level
             * @description Level a tilted horizon or tilted verticals.
             * @default true
             */
            level: boolean;
            /**
             * Perspective
             * @description Make converging verticals (buildings, walls) parallel.
             * @default true
             */
            perspective: boolean;
        };
        /**
         * Blacks
         * @description Move the black point: negative makes blacks deeper, positive lifts them (matte look).
         */
        Blacks: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "blacks";
            /** Amount */
            amount: number;
        };
        /** Body_createDocument */
        Body_createDocument: {
            /** File */
            file: string;
        };
        /** Body_openProject */
        Body_openProject: {
            /** File */
            file?: string | null;
            /** Original */
            original?: string | null;
            /** Graph */
            graph?: string | null;
        };
        /**
         * BrushMask
         * @description Painted by hand: the layer applies where the strokes are.
         */
        BrushMask: {
            /**
             * Invert
             * @description Swap where the layer applies and where it does not.
             * @default false
             */
            invert: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "brush";
            /**
             * Strokes
             * @default []
             */
            strokes: components["schemas"]["BrushStroke"][];
        };
        /** BrushStroke */
        BrushStroke: {
            /** Points */
            points: number[][];
            /**
             * Size
             * @description Brush radius as a fraction of the photo's long edge.
             */
            size: number;
            /**
             * Hardness
             * @description 0 is a soft edge, 100 a hard one.
             * @default 50
             */
            hardness: number;
            /**
             * Erase
             * @description Remove from the mask instead of adding to it.
             * @default false
             */
            erase: boolean;
        };
        /**
         * ChatEntry
         * @description One line of the conversation shown in the chat panel and replayed to the agent.
         *
         *     The conversation is linear even when the history branches: undo, redo, and jumps are
         *     recorded as `event` entries, so the agent knows its earlier change is no longer in effect.
         */
        ChatEntry: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "event";
            /** Text */
            text: string;
            /** Step Id */
            step_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** Checkout */
        Checkout: {
            /**
             * Step Id
             * @description Step to show, or null for the original photo.
             */
            step_id: string | null;
        };
        /**
         * Clarity
         * @description Add (positive) or soften (negative) midtone local contrast and texture.
         */
        Clarity: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "clarity";
            /** Amount */
            amount: number;
        };
        /**
         * ColorGrade
         * @description Split toning, as colorists grade film: tint the shadows, midtones, and highlights
         *     each toward a hue (degrees: 0 red, 30 orange, 60 yellow, 120 green, 180 cyan, 210 teal
         *     blue, 240 blue, 300 magenta) by its own amount, keeping brightness. Teal shadows with
         *     orange highlights is the blockbuster look; warm highlights and cool shadows read as
         *     film.
         */
        ColorGrade: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "color_grade";
            /**
             * Shadows Hue
             * @default 210
             */
            shadows_hue: number;
            /**
             * Shadows
             * @description How strongly the shadows take their hue.
             * @default 0
             */
            shadows: number;
            /**
             * Midtones Hue
             * @default 30
             */
            midtones_hue: number;
            /**
             * Midtones
             * @description How strongly the midtones take their hue.
             * @default 0
             */
            midtones: number;
            /**
             * Highlights Hue
             * @default 40
             */
            highlights_hue: number;
            /**
             * Highlights
             * @description How strongly the highlights take their hue.
             * @default 0
             */
            highlights: number;
            /**
             * Balance
             * @description Moves the split: positive gives highlights more of the range.
             * @default 0
             */
            balance: number;
        };
        /**
         * Colorize
         * @description Colorize a black-and-white photo with an AI colorization model. The photo's own
         *     brightness and detail stay; only color is added. The only operation in its layer.
         */
        Colorize: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * Seed
             * @description The same prompt and seed give the same result; leave it out for a fresh one, or change it for a different take.
             */
            seed?: number | null;
            /**
             * Model
             * @description The model that generates it, recorded by the app.
             * @default
             */
            model: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "colorize";
            /**
             * Amount
             * @description How strong the new colors are.
             * @default 100
             */
            amount: number;
        };
        /**
         * Contrast
         * @description Increase or decrease overall contrast around the midtones.
         */
        Contrast: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "contrast";
            /**
             * Amount
             * @description Positive adds punch; negative flattens.
             */
            amount: number;
        };
        /**
         * Crop
         * @description Crop to a region of the current frame, optionally locked to an aspect ratio.
         *
         *     The box is given as fractions of the current width and height (0 = left/top edge,
         *     1 = right/bottom edge). With an aspect ratio, the result is the largest rectangle of that
         *     ratio centered inside the box, so a full-frame box plus "4:5" is a centered Instagram crop.
         */
        Crop: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "crop";
            /**
             * Left
             * @default 0
             */
            left: number;
            /**
             * Top
             * @default 0
             */
            top: number;
            /**
             * Right
             * @default 1
             */
            right: number;
            /**
             * Bottom
             * @default 1
             */
            bottom: number;
            /**
             * Aspect
             * @description Aspect ratio as width:height.
             * @default free
             * @enum {string}
             */
            aspect: "free" | "original" | "1:1" | "4:5" | "5:4" | "3:4" | "4:3" | "2:3" | "3:2" | "9:16" | "16:9";
        };
        /**
         * Cutout
         * @description Keeps only what the mask selects (the main subject unless told otherwise) and
         *     replaces everything else with transparency or a solid color.
         */
        Cutout: {
            /**
             * Visible
             * @default true
             */
            visible: boolean;
            /**
             * Mask
             * @description What to keep.
             */
            mask?: components["schemas"]["BrushMask"] | components["schemas"]["LinearGradientMask"] | components["schemas"]["RadialGradientMask"] | components["schemas"]["LuminosityMask"] | components["schemas"]["SemanticMask"];
            /**
             * Background
             * @description Null for a transparent background (PNG export), or a color like "#ffffff".
             */
            background?: string | null;
        };
        /**
         * Dehaze
         * @description Cut through haze or fog (positive), or add atmosphere (negative).
         */
        Dehaze: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "dehaze";
            /** Amount */
            amount: number;
        };
        /**
         * Document
         * @description A photo being edited. Stored as JSON next to the original file.
         */
        Document: {
            /** Id */
            id?: string;
            /** Filename */
            filename: string;
            /** Format */
            format: string;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Steps */
            steps?: components["schemas"]["Step"][];
            /** Head */
            head?: string | null;
            /** Tip */
            tip?: string | null;
            /** Chat */
            chat?: components["schemas"]["ChatEntry"][];
        };
        /**
         * DocumentView
         * @description What the web app sees of a document.
         */
        DocumentView: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** Format */
            format: string;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Revision */
            revision: string;
            state: components["schemas"]["EditState"];
            /** Head */
            head: string | null;
            /** Tip */
            tip: string | null;
            /** Can Undo */
            can_undo: boolean;
            /** Can Redo */
            can_redo: boolean;
            /** Undo Label */
            undo_label: string | null;
            /** Redo Label */
            redo_label: string | null;
            /** History */
            history: components["schemas"]["StepView"][];
            /** Chat */
            chat: components["schemas"]["ChatEntry"][];
        };
        /**
         * EditState
         * @description Everything needed to render the photo from the original.
         */
        EditState: {
            /**
             * Framing
             * @default []
             */
            framing: (components["schemas"]["Crop"] | components["schemas"]["Rotate"] | components["schemas"]["Straighten"] | components["schemas"]["Flip"] | components["schemas"]["Perspective"] | components["schemas"]["LensCorrection"] | components["schemas"]["Expand"])[];
            /**
             * Layers
             * @default []
             */
            layers: components["schemas"]["Layer"][];
            cutout?: components["schemas"]["Cutout"] | null;
        };
        /**
         * Expand
         * @description Expand the canvas: extend the photo past its edges, with new surroundings painted by
         *     a generative model to match (outpainting). Use it to turn a vertical photo into a
         *     landscape one, or to give a tight shot more room, without cropping anything away. Masks
         *     and later crops refer to the expanded frame.
         */
        Expand: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * Seed
             * @description The same prompt and seed give the same result; leave it out for a fresh one, or change it for a different take.
             */
            seed?: number | null;
            /**
             * Model
             * @description The model that generates it, recorded by the app.
             * @default
             */
            model: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "expand";
            /**
             * Aspect
             * @description Grow the frame to this width:height, centered on the photo; "free" adds the side amounts below instead.
             * @default free
             * @enum {string}
             */
            aspect: "free" | "1:1" | "4:5" | "5:4" | "3:4" | "4:3" | "2:3" | "3:2" | "9:16" | "16:9";
            /**
             * Left
             * @description Add this fraction of the width on the left.
             * @default 0
             */
            left: number;
            /**
             * Right
             * @description Add this fraction of the width on the right.
             * @default 0
             */
            right: number;
            /**
             * Top
             * @description Add this fraction of the height on top.
             * @default 0
             */
            top: number;
            /**
             * Bottom
             * @description Add this fraction of the height at the bottom.
             * @default 0
             */
            bottom: number;
            /**
             * Prompt
             * @description What the new area should show; empty continues the scene naturally.
             * @default
             */
            prompt: string;
        };
        /** ExportOptions */
        ExportOptions: {
            /**
             * Format
             * @default jpeg
             * @enum {string}
             */
            format: "jpeg" | "png";
            /**
             * Quality
             * @description JPEG quality; ignored for PNG.
             * @default 92
             */
            quality: number;
            /**
             * Keep Location
             * @description Keep GPS location from the original. Off by default for privacy.
             * @default false
             */
            keep_location: boolean;
            /**
             * Upscale
             * @description Enlarge the export with an AI upscaler (up to 8000 pixels across).
             * @default 1
             * @enum {integer}
             */
            upscale: 1 | 2 | 4;
        };
        /**
         * Exposure
         * @description Brighten or darken the whole photo, like changing the camera exposure.
         */
        Exposure: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "exposure";
            /**
             * Stops
             * @description Exposure change in stops; +1 doubles light.
             */
            stops: number;
        };
        /**
         * Flip
         * @description Mirror the photo.
         */
        Flip: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "flip";
            /**
             * Axis
             * @default horizontal
             * @enum {string}
             */
            axis: "horizontal" | "vertical";
        };
        /**
         * Generate
         * @description Generative fill: paint new content where the layer's mask selects, described in
         *     words ("a potted plant", "a sunset sky", "calm water"). The model blends it into the
         *     photo's light and perspective. Needs a mask; it is the only operation in its layer, and
         *     like removals it applies before any adjustment layer.
         */
        Generate: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * Seed
             * @description The same prompt and seed give the same result; leave it out for a fresh one, or change it for a different take.
             */
            seed?: number | null;
            /**
             * Model
             * @description The model that generates it, recorded by the app.
             * @default
             */
            model: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "generate";
            /**
             * Prompt
             * @description What to put there, in plain words.
             */
            prompt: string;
            /**
             * Grow
             * @description How far past the selection's edge to repaint, for a seamless blend.
             * @default 10
             */
            grow: number;
        };
        /**
         * Grain
         * @description Add film-like grain.
         */
        Grain: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "grain";
            /** Amount */
            amount: number;
            /**
             * Size
             * @description Grain size; larger is coarser.
             * @default 25
             */
            size: number;
        };
        /**
         * HSL
         * @description Adjust hue, saturation, and luminance of one color band (e.g. deepen blue skies).
         */
        HSL: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "hsl";
            /**
             * Band
             * @enum {string}
             */
            band: "red" | "orange" | "yellow" | "green" | "aqua" | "blue" | "purple" | "magenta";
            /**
             * Hue
             * @description Shift the band's hue toward its neighbors.
             * @default 0
             */
            hue: number;
            /**
             * Saturation
             * @default 0
             */
            saturation: number;
            /**
             * Luminance
             * @default 0
             */
            luminance: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealBlemishes
         * @description Find small spots (blemishes, pimples, dust) and heal them from the skin around them.
         *     Use on a layer masked to skin.
         */
        HealBlemishes: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "heal_blemishes";
            /**
             * Amount
             * @description How readily spots are healed; higher finds more.
             * @default 50
             */
            amount: number;
            /**
             * Size
             * @description Largest spot to heal; higher heals bigger spots.
             * @default 40
             */
            size: number;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Anthropic Configured */
            anthropic_configured: boolean;
        };
        /**
         * Highlights
         * @description Recover (negative) or boost (positive) the brightest areas without touching shadows.
         */
        Highlights: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "highlights";
            /** Amount */
            amount: number;
        };
        /** JobStatus */
        JobStatus: {
            /** Id */
            id: string;
            /** Doc Id */
            doc_id: string | null;
            /** Task */
            task: string;
            /** Label */
            label: string;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "done" | "failed";
            /** Fraction */
            fraction?: number | null;
            /**
             * Message
             * @default
             */
            message: string;
            /** Backend */
            backend?: string | null;
        };
        /**
         * Layer
         * @description A named group of adjustments with its own visibility, opacity, and blend mode.
         */
        Layer: {
            /**
             * Id
             * @description Stable id; new layers get one from `new_layer_id`.
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Visible
             * @default true
             */
            visible: boolean;
            /**
             * Opacity
             * @description 0 is no effect, 100 is full effect.
             * @default 100
             */
            opacity: number;
            /**
             * Blend Mode
             * @description How the layer's result combines with the layers below: normal replaces them; luminosity changes only brightness (contrast without color shifts); color changes only color; multiply darkens; screen lightens; overlay and soft_light add contrast.
             * @default normal
             * @enum {string}
             */
            blend_mode: "normal" | "multiply" | "screen" | "overlay" | "soft_light" | "color" | "luminosity";
            /**
             * Mask
             * @description Limits the layer to part of the photo; null applies it everywhere.
             */
            mask?: (components["schemas"]["BrushMask"] | components["schemas"]["LinearGradientMask"] | components["schemas"]["RadialGradientMask"] | components["schemas"]["LuminosityMask"] | components["schemas"]["SemanticMask"]) | null;
            /**
             * Operations
             * @default []
             */
            operations: (components["schemas"]["Exposure"] | components["schemas"]["Contrast"] | components["schemas"]["Highlights"] | components["schemas"]["Shadows"] | components["schemas"]["Whites"] | components["schemas"]["Blacks"] | components["schemas"]["WhiteBalance"] | components["schemas"]["Vibrance"] | components["schemas"]["Saturation"] | components["schemas"]["HSL"] | components["schemas"]["Sharpen"] | components["schemas"]["NoiseReduction"] | components["schemas"]["Clarity"] | components["schemas"]["Dehaze"] | components["schemas"]["Vignette"] | components["schemas"]["ColorGrade"] | components["schemas"]["Grain"] | components["schemas"]["ToneCurve"] | components["schemas"]["Remove"] | components["schemas"]["SmoothSkin"] | components["schemas"]["HealBlemishes"] | components["schemas"]["Generate"] | components["schemas"]["ReplaceBackground"] | components["schemas"]["Relight"] | components["schemas"]["RestoreFaces"] | components["schemas"]["Colorize"] | components["schemas"]["Restyle"])[];
        };
        /**
         * LensCorrection
         * @description Undo lens distortion: straight lines that bow outward (barrel, wide angle) or inward
         *     (pincushion, telephoto). Scales up just enough that no edge is left empty.
         */
        LensCorrection: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "lens_correction";
            /**
             * Distortion
             * @description Positive straightens lines that bow outward (barrel); negative straightens lines that bow inward (pincushion).
             * @default 0
             */
            distortion: number;
        };
        /**
         * LinearGradientMask
         * @description Full effect on the `start` side, fading to none at `end`. For skies, use a start at
         *     the top and an end a little below the horizon.
         */
        LinearGradientMask: {
            /**
             * Invert
             * @description Swap where the layer applies and where it does not.
             * @default false
             */
            invert: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "linear";
            /**
             * Start
             * @description [x, y] as fractions of the photo.
             */
            start: number[];
            /**
             * End
             * @description [x, y] as fractions of the photo.
             */
            end: number[];
        };
        /** Look */
        Look: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Operations */
            operations: (components["schemas"]["Exposure"] | components["schemas"]["Contrast"] | components["schemas"]["Highlights"] | components["schemas"]["Shadows"] | components["schemas"]["Whites"] | components["schemas"]["Blacks"] | components["schemas"]["WhiteBalance"] | components["schemas"]["Vibrance"] | components["schemas"]["Saturation"] | components["schemas"]["HSL"] | components["schemas"]["Sharpen"] | components["schemas"]["NoiseReduction"] | components["schemas"]["Clarity"] | components["schemas"]["Dehaze"] | components["schemas"]["Vignette"] | components["schemas"]["ColorGrade"] | components["schemas"]["Grain"] | components["schemas"]["ToneCurve"] | components["schemas"]["Remove"] | components["schemas"]["SmoothSkin"] | components["schemas"]["HealBlemishes"] | components["schemas"]["Generate"] | components["schemas"]["ReplaceBackground"] | components["schemas"]["Relight"] | components["schemas"]["RestoreFaces"] | components["schemas"]["Colorize"] | components["schemas"]["Restyle"])[];
        };
        /** LookStrength */
        LookStrength: {
            /**
             * Strength
             * @description How much of the look to use.
             * @default 100
             */
            strength: number;
        };
        /**
         * LuminosityMask
         * @description Applies to tones between `low` and `high` brightness (0 black, 1 white). For example
         *     0.65 to 1 targets highlights, 0 to 0.35 shadows.
         */
        LuminosityMask: {
            /**
             * Invert
             * @description Swap where the layer applies and where it does not.
             * @default false
             */
            invert: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "luminosity";
            /**
             * Low
             * @default 0
             */
            low: number;
            /**
             * High
             * @default 1
             */
            high: number;
            /**
             * Feather
             * @description Softness of the range edges.
             * @default 0.1
             */
            feather: number;
        };
        /** ManualEdit */
        ManualEdit: {
            /**
             * Label
             * @description Name for the history.
             */
            label: string;
            /** @description The complete edit state after the change. */
            state: components["schemas"]["EditState"];
            /**
             * Coalesce
             * @description What was tweaked, e.g. one slider. Repeated tweaks with the same key update the previous step instead of adding another.
             */
            coalesce?: string | null;
        };
        /** NewRecipe */
        NewRecipe: {
            /** Name */
            name: string;
            /**
             * Layers
             * @description The layers to keep. Brush masks are dropped, since they only fit the photo they were painted on.
             */
            layers: components["schemas"]["Layer"][];
        };
        /**
         * NoiseReduction
         * @description Smooth out grain and color speckles, typical of low-light photos.
         */
        NoiseReduction: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "noise_reduction";
            /**
             * Luminance
             * @description Smooths grainy brightness noise.
             * @default 0
             */
            luminance: number;
            /**
             * Color
             * @description Removes colored speckles.
             * @default 0
             */
            color: number;
        };
        /** OperationSpec */
        OperationSpec: {
            /** Op */
            op: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /**
             * Group
             * @enum {string}
             */
            group: "light" | "color" | "detail" | "framing" | "finishing" | "retouch" | "generative";
            /** Framing */
            framing: boolean;
            /** Params */
            params: components["schemas"]["ParamSpec"][];
        };
        /** ParamSpec */
        ParamSpec: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "number" | "choice" | "curve" | "text" | "seed";
            /**
             * Description
             * @default
             */
            description: string;
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /** Step */
            step?: number | null;
            /** Choices */
            choices?: (string | number)[] | null;
            /** Default */
            default?: unknown;
        };
        /**
         * Perspective
         * @description Fix lines that converge because the camera was tilted: buildings that lean in toward
         *     the top, or a wall that shrinks toward one side. The narrow side is stretched out to the
         *     frame, so nothing is left empty.
         */
        Perspective: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "perspective";
            /**
             * Vertical
             * @description Positive widens the top, for verticals that lean in toward the top (camera tilted up); negative widens the bottom.
             * @default 0
             */
            vertical: number;
            /**
             * Horizontal
             * @description Positive widens the right side, for lines that converge toward the right; negative widens the left.
             * @default 0
             */
            horizontal: number;
        };
        /**
         * RadialGradientMask
         * @description Full effect inside an ellipse, fading out toward its edge. Invert it to affect
         *     everything outside instead (for example, to darken around a subject).
         */
        RadialGradientMask: {
            /**
             * Invert
             * @description Swap where the layer applies and where it does not.
             * @default false
             */
            invert: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "radial";
            /**
             * Center
             * @description [x, y] as fractions of the photo.
             */
            center: number[];
            /**
             * Radius X
             * @description Half-width as a fraction of photo width.
             */
            radius_x: number;
            /**
             * Radius Y
             * @description Half-height as a fraction of photo height.
             */
            radius_y: number;
            /**
             * Feather
             * @description How gradually the edge fades.
             * @default 50
             */
            feather: number;
        };
        /** Recipe */
        Recipe: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Layers */
            layers: components["schemas"]["Layer"][];
        };
        /**
         * Relight
         * @description Change the light: where it comes from and its mood ("warm sunset light", "cool
         *     moonlight", "neon purple"), as an AI relighting model imagines the scene lit that way.
         *     Best for portraits and products; give the layer a mask on the subject to relight only
         *     it. Fine detail stays from the photo. The only operation in its layer.
         */
        Relight: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * Seed
             * @description The same prompt and seed give the same result; leave it out for a fresh one, or change it for a different take.
             */
            seed?: number | null;
            /**
             * Model
             * @description The model that generates it, recorded by the app.
             * @default
             */
            model: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "relight";
            /**
             * Direction
             * @description Where the light comes from; back is a rim light from behind.
             * @default left
             * @enum {string}
             */
            direction: "left" | "right" | "top" | "bottom" | "front" | "back";
            /**
             * Prompt
             * @description The light's color and mood; empty is soft daylight.
             * @default
             */
            prompt: string;
            /**
             * Amount
             * @description How much of the new light to use.
             * @default 60
             */
            amount: number;
        };
        /**
         * Remove
         * @description Remove what the layer's mask selects (a person, power lines, a sign) and fill the gap
         *     with plausible surroundings, using an AI inpainting model. Needs a mask; it is the only
         *     operation in its layer. Removal layers apply first, before any adjustment layer.
         */
        Remove: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "remove";
            /**
             * Grow
             * @description How far past the selection's edge to fill, so outlines and halos go.
             * @default 20
             */
            grow: number;
        };
        /**
         * ReplaceBackground
         * @description Replace the background with a new scene described in words ("a sunlit beach",
         *     "a softly lit studio, pale gray"), painted around the subject so its perspective fits,
         *     and match the subject's light and color to it. The layer's mask selects what to
         *     replace; without one, everything but the main subject. The only operation in its layer;
         *     applies before adjustments.
         */
        ReplaceBackground: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * Seed
             * @description The same prompt and seed give the same result; leave it out for a fresh one, or change it for a different take.
             */
            seed?: number | null;
            /**
             * Model
             * @description The model that generates it, recorded by the app.
             * @default
             */
            model: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "replace_background";
            /**
             * Prompt
             * @description The new background.
             */
            prompt: string;
            /**
             * Harmonize
             * @description How much to match the subject's light and color to the new scene.
             * @default 50
             */
            harmonize: number;
        };
        /**
         * RestoreFaces
         * @description Restore faces in an old, blurry, or low-resolution photo with an AI face restoration
         *     model: sharper eyes, skin, and hair that still look like the person. Only faces change.
         *     The only operation in its layer.
         */
        RestoreFaces: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * Seed
             * @description The same prompt and seed give the same result; leave it out for a fresh one, or change it for a different take.
             */
            seed?: number | null;
            /**
             * Model
             * @description The model that generates it, recorded by the app.
             * @default
             */
            model: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "restore_faces";
            /**
             * Amount
             * @description How much of the restored faces to use; lower keeps more of the original.
             * @default 70
             */
            amount: number;
        };
        /**
         * Restyle
         * @description Redraw the whole photo in a style ("watercolor painting", "1970s film photo",
         *     "Studio Ghibli anime") with an image generation model, keeping its composition. Use
         *     only when asked for a new style or medium; for a color look, use color_grade and the
         *     other adjustments instead. The only operation in its layer.
         */
        Restyle: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * Seed
             * @description The same prompt and seed give the same result; leave it out for a fresh one, or change it for a different take.
             */
            seed?: number | null;
            /**
             * Model
             * @description The model that generates it, recorded by the app.
             * @default
             */
            model: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "restyle";
            /**
             * Prompt
             * @description The style to redraw it in.
             */
            prompt: string;
            /**
             * Strength
             * @description How far it may stray from the photo; higher is more stylized.
             * @default 50
             */
            strength: number;
        };
        /**
         * Retouch
         * @description How much of each retouch to do; 0 leaves that part out.
         */
        Retouch: {
            /**
             * Smooth Skin
             * @description Soften skin, keeping texture.
             * @default 35
             */
            smooth_skin: number;
            /**
             * Remove Blemishes
             * @description Heal small spots on the skin.
             * @default true
             */
            remove_blemishes: boolean;
            /**
             * Brighten Eyes
             * @description Brighten and clarify eyes.
             * @default 25
             */
            brighten_eyes: number;
            /**
             * Whiten Teeth
             * @description Take the yellow out of teeth.
             * @default 25
             */
            whiten_teeth: number;
        };
        /**
         * Rotate
         * @description Rotate the photo clockwise by a quarter, half, or three-quarter turn.
         */
        Rotate: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "rotate";
            /**
             * Degrees
             * @enum {integer}
             */
            degrees: 90 | 180 | 270;
        };
        /**
         * Saturation
         * @description Uniformly increase or decrease color intensity; -100 makes black and white.
         */
        Saturation: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "saturation";
            /** Amount */
            amount: number;
        };
        /** SelectPoint */
        SelectPoint: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /**
             * Include
             * @description False marks a spot that is not part of it.
             * @default true
             */
            include: boolean;
        };
        /**
         * SemanticMask
         * @description Selects something by what it is, found by an AI model: the sky, the main subject,
         *     people, a particular object, or parts of a face. For `object`, give a `box` around it
         *     (and optionally `points` on it), in fractions of the photo as you see it.
         */
        SemanticMask: {
            /**
             * Invert
             * @description Swap where the layer applies and where it does not.
             * @default false
             */
            invert: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "semantic";
            /**
             * Target
             * @description subject: the main subject, as a cutout would keep it; people: every person; sky; object: one thing you point at with `box` and/or `points` (a particular person, a dog, a car); and parts of faces for portraits: skin (face and visible skin), face, eyes, lips, teeth, hair.
             * @enum {string}
             */
            target: "subject" | "people" | "sky" | "object" | "skin" | "face" | "eyes" | "lips" | "teeth" | "hair";
            /**
             * Box
             * @description For object: [left, top, right, bottom] around it, fractions of the photo.
             */
            box?: number[] | null;
            /**
             * Points
             * @description For object: spots on it (or, with include false, not).
             * @default []
             */
            points: components["schemas"]["SelectPoint"][];
            /**
             * Description
             * @description What is selected, in plain words: "the dog".
             * @default
             */
            description: string;
            /**
             * Strokes
             * @description Brush touch-ups painted by the person over what the model found: added where painted, taken away where erased. Keep them when changing the mask.
             * @default []
             */
            strokes: components["schemas"]["BrushStroke"][];
        };
        /**
         * Shadows
         * @description Lift (positive) or deepen (negative) the darkest areas without touching highlights.
         */
        Shadows: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "shadows";
            /** Amount */
            amount: number;
        };
        /**
         * Sharpen
         * @description Sharpen edges and fine detail.
         */
        Sharpen: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "sharpen";
            /**
             * Amount
             * @description Strength; 25-50 is typical.
             */
            amount: number;
            /**
             * Radius
             * @description Detail size in full-res pixels.
             * @default 1
             */
            radius: number;
        };
        /**
         * SmoothSkin
         * @description Soften skin while keeping its natural texture (pores, fine lines stay, blotches and
         *     uneven tone go). Use on a layer masked to skin; subtle amounts (20-40) look natural.
         */
        SmoothSkin: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "smooth_skin";
            /**
             * Amount
             * @description How much to smooth.
             * @default 35
             */
            amount: number;
            /**
             * Texture
             * @description How much fine skin texture to keep.
             * @default 60
             */
            texture: number;
        };
        /**
         * Step
         * @description One named change to the photo and the edit state it left behind.
         */
        Step: {
            /** Id */
            id?: string;
            /** Parent */
            parent?: string | null;
            /**
             * Kind
             * @default agent
             * @enum {string}
             */
            kind: "agent" | "manual";
            /** Label */
            label: string;
            /**
             * Request
             * @default
             */
            request: string;
            /**
             * Reply
             * @default
             */
            reply: string;
            state?: components["schemas"]["EditState"];
            /** Coalesce */
            coalesce?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** StepView */
        StepView: {
            /** Id */
            id: string;
            /** Parent */
            parent: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "agent" | "manual";
            /** Label */
            label: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Active */
            active: boolean;
        };
        /**
         * Straighten
         * @description Rotate by a small angle to level a tilted horizon, cropping away the empty corners.
         */
        Straighten: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "straighten";
            /**
             * Angle
             * @description Degrees; positive turns clockwise.
             */
            angle: number;
        };
        /** TaskStatus */
        TaskStatus: {
            /** Task */
            task: string;
            /** Label */
            label: string;
            /** Backend */
            backend: string;
            /** License */
            license: string;
            /** Uses Weights */
            uses_weights: boolean;
        };
        /**
         * ToneCurve
         * @description Remap tones with a curve through control points (input, output), both 0..1.
         *
         *     The curve always passes through its points in order of input. An S-shape adds contrast;
         *     lifting the (0, y) point gives faded blacks.
         */
        ToneCurve: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "tone_curve";
            /**
             * Points
             * @description [input, output] pairs.
             */
            points: number[][];
            /**
             * Channel
             * @default rgb
             * @enum {string}
             */
            channel: "rgb" | "red" | "green" | "blue";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Vibrance
         * @description Boost or reduce saturation mostly in muted colors, protecting skin and saturated areas.
         */
        Vibrance: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "vibrance";
            /** Amount */
            amount: number;
        };
        /**
         * Vignette
         * @description Darken (negative) or lighten (positive) the edges to draw the eye inward.
         */
        Vignette: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "vignette";
            /** Amount */
            amount: number;
            /**
             * Midpoint
             * @description How far in the effect reaches; lower is wider.
             * @default 50
             */
            midpoint: number;
        };
        /**
         * WhiteBalance
         * @description Shift color temperature and tint to fix a color cast or set a mood.
         */
        WhiteBalance: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "white_balance";
            /**
             * Temperature
             * @description Positive is warmer (yellow), negative cooler.
             * @default 0
             */
            temperature: number;
            /**
             * Tint
             * @description Positive is more magenta, negative more green.
             * @default 0
             */
            tint: number;
        };
        /**
         * Whites
         * @description Move the white point: positive makes the brightest tones brighter, negative dims them.
         */
        Whites: {
            /**
             * Id
             * @description Stable id of this operation.
             */
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "whites";
            /** Amount */
            amount: number;
        };
        /** WorkerStatus */
        WorkerStatus: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "process" | "inline";
            /** Device */
            device: string;
            /** Tasks */
            tasks: components["schemas"]["TaskStatus"][];
        };
        /** AgentError */
        AgentError: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            /** Message */
            message: string;
        };
        /** OperationEvent */
        OperationEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "operation";
            /**
             * Action
             * @enum {string}
             */
            action: "added" | "updated" | "removed";
            /** Summary */
            summary: string;
        };
        /** TextDelta */
        TextDelta: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Text */
            text: string;
        };
        /** TurnDone */
        TurnDone: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "done";
            document: components["schemas"]["DocumentView"];
        };
        /** TurnStarted */
        TurnStarted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "turn_started";
        };
        ChatEvent: components["schemas"]["TurnStarted"] | components["schemas"]["TextDelta"] | components["schemas"]["OperationEvent"] | components["schemas"]["TurnDone"] | components["schemas"]["AgentError"];
        /**
         * ChatMessage
         * @description What the browser sends over the chat WebSocket.
         */
        ChatMessage: {
            /**
             * Type
             * @default message
             * @constant
             */
            type: "message";
            /** Text */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_createDocument"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"];
                };
            };
            /** @description File too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a photo */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    downloadProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.photo-agent.project+zip": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getGraph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                    "image/png": unknown;
                    "image/heic": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    editByHand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    applyRecipe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"];
                };
            };
            /** @description No such document or recipe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    applyLook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
                look_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LookStrength"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"];
                };
            };
            /** @description No such document or look */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retouchPortrait: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Retouch"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    autoStraighten: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AutoStraighten"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Checkout"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"];
                };
            };
            /** @description No such document or step */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getOriginal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPreview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exportDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportOptions"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getBefore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getLayerMask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
                layer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description No such layer */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listJobs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    openProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_openProject"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"];
                };
            };
            /** @description File too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a project or photo */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listRecipes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"][];
                };
            };
        };
    };
    createRecipe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewRecipe"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteRecipe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such recipe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listLooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Look"][];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listOperations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationSpec"][];
                };
            };
        };
    };
    getModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerStatus"];
                };
            };
        };
    };
}
